{
  "__PACKAGE_UIDS__", "",
  "__LOCALS_IN_TRACEBACK__", "",
  "__ARRAY_RESERVED_WORD__", "",
  "__CFG_MAX_LOCAL_VARIABLES__", "40",
  "__DEFAULT_DB__", "USE_MYSQL",
  "__SUPPRESS_ARGUMENT_WARNINGS__", "",
  "__CALLOUT_HANDLES__", "",
  "__SAVE_EXTENSION__", "\".o\"",
  "__DEFAULT_PRAGMAS__", "PRAGMA_WARNINGS + PRAGMA_ERROR_CONTEXT + PRAGMA_SAVE_BINARY + PRAGMA_STRICT_TYPES",
  "__CONFIG_FILE_DIR__", "\"/u/tim/COMP/bin\"",
  "__HEARTBEAT_INTERVAL__", "2000000",
  "__NO_LIGHT__", "",
  "__RESTRICTED_ED__", "",
  "__ARRAY_STATS__", "",
  "__ARGUMENTS_IN_TRACEBACK__", "",
  "__AUTO_TRUST_BACKBONE__", "",
  "__SMALL_STRING_SIZE__", "100",
  "__HEART_BEAT_CHUNK__", "32",
  "__PACKAGE_CONTRIB__", "",
  "__PACKAGE_DB__", "",
  "__OLD_ED__", "",
  "__CACHE_STATS__", "",
  "__LARGE_STRING_SIZE__", "1000",
  "__APPLY_CACHE_BITS__", "12",
  "__BINARIES__", "",
  "__STRING_STATS__", "",
  "__NO_ANSI__", "",
  "__SANE_EXPLODE_STRING__", "",
  "__CFG_MAX_CALL_DEPTH__", "50",
  "__LOG_CATCHES__", "",
  "__MAX_SAVE_SVALUE_DEPTH__", "25",
  "__MUDLIB_ERROR_HANDLER__", "",
  "__CFG_EVALUATOR_STACK_SIZE__", "1000",
  "__CALLOUT_CYCLE_SIZE__", "32",
  "__LPC_TO_C__", "",
  "__PACKAGE_SOCKETS__", "",
  "__CFG_LIVING_HASH_SIZE__", "256",
  "__THIS_PLAYER_IN_CALL_OUT__", "",
  "__NONINTERACTIVE_STDERR_WRITE__", "",
  "___OPTIONS_H___", "",
  "__REF_RESERVED_WORD__", "",
  "__MESSAGE_BUFFER_SIZE__", "4096",
  "__SMALLOC__", "",
  "__STRIP_BEFORE_PROCESS_INPUT__", "",
  "__USE_MYSQL__", "2",
  "__NEXT_MALLOC_DEBUG__", "",
  "__AUTO_SETEUID__", "",
  "__TRAP_CRASHES__", "",
  "__LARGEST_PRINTABLE_STRING__", "8192",
  "__CUSTOM_CRYPT__", "",
  "__PACKAGE_DEVELOP__", "",
  "__PACKAGE_MATH__", "",
};

#define NUM_OPTION_DEFS 52

